name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version you want to use

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend/obrigado-react-js

      - name: Build
        run: npm run build
        working-directory: ./frontend/obrigado-react-js

      - name: Vercel Action
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Set the Vercel token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Set the Vercel org id
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Set the Vercel project id
          vercel-args: '--prod' # Additional arguments for the Vercel CLI
        env:
          CI: true
